name: Build and Deploy UI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-ui:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js v20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json
        
    - name: Install dependencies
      run: |
        cd ui
        npm ci --legacy-peer-deps
        
    - name: Rebuild sharp for current environment
      run: |
        cd ui
        npm rebuild sharp
        
    - name: Build UI
      run: |
        cd ui
        npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ui-build
        path: ui/out/
        retention-days: 7

  lint-ui:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js v20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json
        
    - name: Install dependencies
      run: |
        cd ui
        npm ci --legacy-peer-deps
        
    - name: Run linting
      run: |
        cd ui
        npm run lint